const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const clean=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
const validHandle=value=>/^[a-z0-9_]{3,24}$/.test(value);
const empty=()=>({profiles:{},handles:{},playlists:{},activities:[]});
const normalize=current=>({...empty(),...(current??{}),activities:Array.isArray(current?.activities)?current.activities:[]});
const safeTrack=track=>track&&/^[-\w]{6,20}$/.test(track.id)&&clean(track.title,200)?{id:track.id,title:clean(track.title,200),artist:clean(track.artist,160),album:clean(track.album,160),duration:clean(track.duration,20),artwork:/^https:\/\//.test(track.artwork??'')?clean(track.artwork,500):'',accent:clean(track.accent,20)}:null;
const publicProfile=(profile,viewer)=>({handle:profile.handle,displayName:profile.displayName,bio:profile.bio,avatar:profile.avatar,followers:profile.followers.length,following:profile.following.length,followedByMe:profile.followers.includes(viewer),matchReady:Boolean(profile.taste?.length)});
const publicPlaylist=(playlist,viewer)=>({id:playlist.id,title:playlist.title,ownerHandle:playlist.ownerHandle,members:playlist.members,tracks:playlist.tracks,updatedAt:playlist.updatedAt,canEdit:playlist.owner===viewer||playlist.memberIds.includes(viewer),...(playlist.owner===viewer?{inviteToken:playlist.inviteToken}:{})});
const addActivity=(state,actor,type,data={})=>{state.activities.unshift({id:crypto.randomUUID(),actor,type,...data,at:new Date().toISOString()});state.activities=state.activities.slice(0,200);};
const presentActivity=(state,item)=>{const actor=state.profiles[item.actor];if(!actor)return null;return{id:item.id,type:item.type,actorHandle:actor.handle,actorName:actor.displayName,actorAvatar:actor.avatar,playlistTitle:item.playlistTitle,track:item.track,at:item.at};};
export function socialPublic(current,viewer){const state=normalize(current),me=state.profiles[viewer],circle=new Set([viewer,...(me?.following??[])]);return {me:me?publicProfile(me,viewer):null,profiles:Object.values(state.profiles).filter(item=>item.id!==viewer).map(item=>publicProfile(item,viewer)),playlists:Object.values(state.playlists).filter(item=>item.owner===viewer||item.memberIds.includes(viewer)).map(item=>publicPlaylist(item,viewer)),feed:state.activities.filter(item=>circle.has(item.actor)).map(item=>presentActivity(state,item)).filter(Boolean).slice(0,40)};}
export function publicSocialProfile(current,handle){const state=normalize(current),id=state.handles[clean(handle,24).toLowerCase()],profile=state.profiles[id];if(!profile)return null;return{profile:publicProfile(profile,''),activity:state.activities.filter(item=>item.actor===id).map(item=>presentActivity(state,item)).filter(Boolean).slice(0,20),playlists:Object.values(state.playlists).filter(item=>item.owner===id).map(item=>({id:item.id,title:item.title,tracks:item.tracks.length,updatedAt:item.updatedAt}))};}
export function socialMatch(current,viewer,handle){const state=normalize(current),me=state.profiles[viewer],target=state.profiles[state.handles[clean(handle,24).toLowerCase()]];if(!me||!target||target.id===viewer)fail('Perfil não encontrado.',404);if(!me.taste?.length||!target.taste?.length)fail('Os dois perfis precisam ativar o Aurora Match.',409);const mine=new Map(me.taste.map(track=>[track.id,track])),theirs=new Map(target.taste.map(track=>[track.id,track])),shared=[...mine.keys()].filter(id=>theirs.has(id)).map(id=>mine.get(id));const myArtists=new Set(me.taste.map(track=>track.artist.toLowerCase()).filter(Boolean)),theirArtists=new Set(target.taste.map(track=>track.artist.toLowerCase()).filter(Boolean)),sharedArtists=[...myArtists].filter(value=>theirArtists.has(value));const trackUnion=new Set([...mine.keys(),...theirs.keys()]).size,artistUnion=new Set([...myArtists,...theirArtists]).size;const trackScore=trackUnion?shared.length/trackUnion:0,artistScore=artistUnion?sharedArtists.length/artistUnion:0,score=Math.round((trackScore*.7+artistScore*.3)*100);return{score,with:{handle:target.handle,displayName:target.displayName,avatar:target.avatar},sharedTracks:shared.slice(0,8),sharedArtists:sharedArtists.slice(0,8),discoveries:target.taste.filter(track=>!mine.has(track.id)).slice(0,8),explanation:`${shared.length} faixas e ${sharedArtists.length} artistas em comum entre ${mine.size} e ${theirs.size} referências.`};}
const matchPlaylistTracks=(mine,theirs)=>{const result=[],seen=new Set();const add=track=>{if(track&&!seen.has(track.id)){seen.add(track.id);result.push(track);}};mine.filter(track=>theirs.some(item=>item.id===track.id)).forEach(add);for(let index=0;result.length<20&&(index<mine.length||index<theirs.length);index++){add(mine[index]);add(theirs[index]);}return result.slice(0,20);};
export function applySocialAction(current,viewer,body){const state=structuredClone(normalize(current)),action=body?.type;
  if(action==='profile'){const handle=clean(body.handle,24).toLowerCase();if(!validHandle(handle))fail('Use de 3 a 24 letras, números ou _.');const taken=state.handles[handle];if(taken&&taken!==viewer)fail('Este @usuário já está em uso.',409);const old=state.profiles[viewer];if(old?.handle&&old.handle!==handle)delete state.handles[old.handle];state.handles[handle]=viewer;state.profiles[viewer]={id:viewer,handle,displayName:clean(body.displayName,60)||handle,bio:clean(body.bio,160),avatar:/^https:\/\//.test(body.avatar??'')?clean(body.avatar,500):'',followers:old?.followers??[],following:old?.following??[],taste:old?.taste??[]};if(!old)addActivity(state,viewer,'joined');}
  else {const me=state.profiles[viewer];if(!me)fail('Crie seu perfil primeiro.',409);
    if(action==='follow'){const targetId=state.handles[clean(body.handle,24).toLowerCase()];const target=state.profiles[targetId];if(!target||targetId===viewer)fail('Perfil não encontrado.',404);const following=body.following!==false;if(following){if(!me.following.includes(targetId)){me.following.push(targetId);target.followers.push(viewer);addActivity(state,viewer,'followed',{targetHandle:target.handle});}}else{me.following=me.following.filter(id=>id!==targetId);target.followers=target.followers.filter(id=>id!==viewer);}}
    else if(action==='sync-taste'){if(!Array.isArray(body.tracks))fail('Seleção musical inválida.');me.taste=body.tracks.slice(0,50).map(safeTrack).filter(Boolean);if(me.taste.length<3)fail('Escolha pelo menos 3 músicas para ativar o Match.');}
    else if(action==='create-match-playlist'){const targetId=state.handles[clean(body.handle,24).toLowerCase()],target=state.profiles[targetId];if(!target||targetId===viewer)fail('Perfil não encontrado.',404);if(!me.taste?.length||!target.taste?.length)fail('Os dois perfis precisam ativar o Aurora Match.',409);const title=`Match: ${me.displayName} + ${target.displayName}`.slice(0,80),id=crypto.randomUUID(),now=new Date().toISOString(),tracks=matchPlaylistTracks(me.taste,target.taste).map((track,index)=>({track,addedBy:index%2?target.handle:me.handle,addedAt:now}));state.playlists[id]={id,title,owner:viewer,ownerHandle:me.handle,memberIds:[targetId],members:[target.handle],tracks,inviteToken:crypto.randomUUID(),updatedAt:now};addActivity(state,viewer,'playlist',{playlistTitle:title});}
    else if(action==='create-playlist'){const title=clean(body.title,80);if(!title)fail('Dê um nome à playlist.');const id=crypto.randomUUID();state.playlists[id]={id,title,owner:viewer,ownerHandle:me.handle,memberIds:[],members:[],tracks:[],inviteToken:crypto.randomUUID(),updatedAt:new Date().toISOString()};addActivity(state,viewer,'playlist',{playlistTitle:title});}
    else if(action==='invite'){const playlist=state.playlists[body.playlistId];if(!playlist||playlist.owner!==viewer)fail('Playlist não encontrada.',404);const targetId=state.handles[clean(body.handle,24).toLowerCase()];const target=state.profiles[targetId];if(!target)fail('Perfil não encontrado.',404);if(targetId!==viewer&&!playlist.memberIds.includes(targetId)){playlist.memberIds.push(targetId);playlist.members.push(target.handle);playlist.updatedAt=new Date().toISOString();}}
    else if(action==='join-playlist'){const token=clean(body.token,80);const playlist=Object.values(state.playlists).find(item=>item.inviteToken===token);if(!playlist)fail('Convite inválido ou expirado.',404);if(playlist.owner!==viewer&&!playlist.memberIds.includes(viewer)){playlist.memberIds.push(viewer);playlist.members.push(me.handle);playlist.updatedAt=new Date().toISOString();addActivity(state,viewer,'joined-playlist',{playlistTitle:playlist.title});}}
    else if(action==='rotate-invite'){const playlist=state.playlists[body.playlistId];if(!playlist||playlist.owner!==viewer)fail('Playlist não encontrada.',404);playlist.inviteToken=crypto.randomUUID();playlist.updatedAt=new Date().toISOString();}
    else if(action==='add-track'){const playlist=state.playlists[body.playlistId];if(!playlist||(playlist.owner!==viewer&&!playlist.memberIds.includes(viewer)))fail('Sem permissão para editar.',403);const track=safeTrack(body.track);if(!track)fail('Faixa inválida.');if(!playlist.tracks.some(item=>item.track.id===track.id)){playlist.tracks.push({track,addedBy:me.handle,addedAt:new Date().toISOString()});addActivity(state,viewer,'track',{playlistTitle:playlist.title,track});}playlist.updatedAt=new Date().toISOString();}
    else fail('Ação social inválida.');}
  return state;
}
