const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const clean=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
const validHandle=value=>/^[a-z0-9_]{3,24}$/.test(value);
const publicProfile=(profile,viewer)=>({handle:profile.handle,displayName:profile.displayName,bio:profile.bio,avatar:profile.avatar,followers:profile.followers.length,following:profile.following.length,followedByMe:profile.followers.includes(viewer)});
const publicPlaylist=(playlist,viewer)=>({...playlist,owner:undefined,memberIds:undefined,canEdit:playlist.owner===viewer||playlist.memberIds.includes(viewer)});
export function socialPublic(state,viewer){const value=state??{profiles:{},handles:{},playlists:{}};const me=value.profiles[viewer];return {me:me?publicProfile(me,viewer):null,profiles:Object.values(value.profiles).filter(item=>item.id!==viewer).map(item=>publicProfile(item,viewer)),playlists:Object.values(value.playlists).filter(item=>item.owner===viewer||item.memberIds.includes(viewer)).map(item=>publicPlaylist(item,viewer))};}
export function applySocialAction(current,viewer,body){const state=structuredClone(current??{profiles:{},handles:{},playlists:{}});const action=body?.type;
  if(action==='profile'){const handle=clean(body.handle,24).toLowerCase();if(!validHandle(handle))fail('Use de 3 a 24 letras, números ou _.');const taken=state.handles[handle];if(taken&&taken!==viewer)fail('Este @usuário já está em uso.',409);const old=state.profiles[viewer];if(old?.handle&&old.handle!==handle)delete state.handles[old.handle];state.handles[handle]=viewer;state.profiles[viewer]={id:viewer,handle,displayName:clean(body.displayName,60)||handle,bio:clean(body.bio,160),avatar:/^https:\/\//.test(body.avatar??'')?clean(body.avatar,500):'',followers:old?.followers??[],following:old?.following??[]};}
  else {const me=state.profiles[viewer];if(!me)fail('Crie seu perfil primeiro.',409);
    if(action==='follow'){const targetId=state.handles[clean(body.handle,24).toLowerCase()];const target=state.profiles[targetId];if(!target||targetId===viewer)fail('Perfil não encontrado.',404);const following=body.following!==false;if(following){if(!me.following.includes(targetId))me.following.push(targetId);if(!target.followers.includes(viewer))target.followers.push(viewer);}else{me.following=me.following.filter(id=>id!==targetId);target.followers=target.followers.filter(id=>id!==viewer);}}
    else if(action==='create-playlist'){const title=clean(body.title,80);if(!title)fail('Dê um nome à playlist.');const id=crypto.randomUUID();state.playlists[id]={id,title,owner:viewer,ownerHandle:me.handle,memberIds:[],members:[],tracks:[],updatedAt:new Date().toISOString()};}
    else if(action==='invite'){const playlist=state.playlists[body.playlistId];if(!playlist||playlist.owner!==viewer)fail('Playlist não encontrada.',404);const targetId=state.handles[clean(body.handle,24).toLowerCase()];const target=state.profiles[targetId];if(!target)fail('Perfil não encontrado.',404);if(targetId!==viewer&&!playlist.memberIds.includes(targetId)){playlist.memberIds.push(targetId);playlist.members.push(target.handle);playlist.updatedAt=new Date().toISOString();}}
    else if(action==='add-track'){const playlist=state.playlists[body.playlistId];if(!playlist||(playlist.owner!==viewer&&!playlist.memberIds.includes(viewer)))fail('Sem permissão para editar.',403);const track=body.track;if(!track||!/^[-\w]{6,20}$/.test(track.id)||!clean(track.title,200))fail('Faixa inválida.');if(!playlist.tracks.some(item=>item.track.id===track.id))playlist.tracks.push({track:{id:track.id,title:clean(track.title,200),artist:clean(track.artist,160),album:clean(track.album,160),duration:clean(track.duration,20),artwork:/^https:\/\//.test(track.artwork??'')?clean(track.artwork,500):'',accent:clean(track.accent,20)},addedBy:me.handle,addedAt:new Date().toISOString()});playlist.updatedAt=new Date().toISOString();}
    else fail('Ação social inválida.');}
  return state;
}
