import test from 'node:test';
import assert from 'node:assert/strict';
import {applyLibraryAction,publicLibrary} from '../src/library-state.js';

const track={id:'aaaaaaaaaaa',title:'Faixa',artist:'Artista',album:'YouTube',duration:'3:00',artwork:'https://example.com/a.jpg',accent:'#7c5cff'};
test('imports each browser library once and preserves the union',()=>{let state=applyLibraryAction(null,{type:'import',deviceId:'device-browser-a',tracks:[track]});state=applyLibraryAction(state,{type:'import',deviceId:'device-browser-a',tracks:[]});assert.deepEqual(publicLibrary(state).likedTracks,[track]);assert.equal(state.revision,1);});
test('like actions synchronize additions and removals',()=>{let state=applyLibraryAction(null,{type:'like',track,liked:true});assert.equal(publicLibrary(state).likedTracks.length,1);state=applyLibraryAction(state,{type:'like',track,liked:false});assert.equal(publicLibrary(state).likedTracks.length,0);assert.equal(state.revision,2);});
test('rejects malformed and oversized imports',()=>{assert.throws(()=>applyLibraryAction(null,{type:'like',track:{id:'bad'},liked:true}),/Curtida inválida/);assert.throws(()=>applyLibraryAction(null,{type:'import',deviceId:'device-browser-a',tracks:Array(501).fill(track)}),/Biblioteca inválida/);});
test('synchronizes playlists and recent tracks across devices',()=>{const collection={id:'mix-1',title:'Meu mix',tracks:[track]};let state=applyLibraryAction(null,{type:'import',deviceId:'device-browser-a',tracks:[],collections:[collection],recent:[track]});assert.deepEqual(publicLibrary(state).collections,[collection]);assert.deepEqual(publicLibrary(state).recent,[track]);const updated={...collection,title:'Nosso mix'};state=applyLibraryAction(state,{type:'collection',collection:updated});assert.equal(publicLibrary(state).collections[0].title,'Nosso mix');state=applyLibraryAction(state,{type:'recent',track:{...track,id:'bbbbbbbbbbb'}});assert.deepEqual(publicLibrary(state).recent.map(item=>item.id),['bbbbbbbbbbb','aaaaaaaaaaa']);});
test('repeat imports merge new local data without duplicating previous items',()=>{let state=applyLibraryAction(null,{type:'import',deviceId:'device-browser-a',tracks:[track],collections:[],recent:[]});const other={...track,id:'bbbbbbbbbbb'};state=applyLibraryAction(state,{type:'import',deviceId:'device-browser-a',tracks:[track,other],collections:[],recent:[other]});assert.deepEqual(publicLibrary(state).likedTracks.map(item=>item.id).sort(),['aaaaaaaaaaa','bbbbbbbbbbb']);assert.equal(publicLibrary(state).recent.length,1);});
