import fs from 'node:fs/promises';import os from 'node:os';import process from 'node:process';import readline from 'node:readline/promises';
import {activityKey,toDiscordActivity} from './activity.mjs';
import {protectSecret,unprotectSecret} from './secrets.mjs';
import {createSocialSdkClient,socialSdkAvailable} from './social-sdk-client.mjs';
import {appId,configDir,configPath,endpoint,runtimePath} from './settings.mjs';

async function readConfig(){try{return JSON.parse(await fs.readFile(configPath,'utf8'));}catch{return {};}}
async function saveConfig(value){await fs.mkdir(configDir,{recursive:true});await fs.writeFile(configPath,JSON.stringify(value,null,2),{mode:0o600});}
async function saveRuntime(value){await fs.mkdir(configDir,{recursive:true});await fs.writeFile(runtimePath,JSON.stringify(value),{mode:0o600});}
async function clearRuntime(){try{const value=JSON.parse(await fs.readFile(runtimePath,'utf8'));if(value.pid===process.pid)await fs.unlink(runtimePath);}catch{/* Runtime state is disposable. */}}
async function createRpcClient(){const {default:DiscordRPC}=await import('discord-rpc');DiscordRPC.register(appId);const rpc=new DiscordRPC.Client({transport:'ipc'});await new Promise((resolve,reject)=>{rpc.once('ready',resolve);rpc.once('error',reject);void rpc.login({clientId:appId}).catch(reject);});return {transport:'rpc',setActivity:value=>rpc.setActivity(value),clearActivity:()=>rpc.clearActivity(),destroy:()=>rpc.destroy()};}
async function createDiscordClient(){if(process.env.AURORA_DISCORD_TRANSPORT!=='rpc'&&socialSdkAvailable()){try{return await createSocialSdkClient(appId);}catch(error){console.error(`[Aurora] Social SDK indisponível (${error.message}); usando RPC.`);}}return createRpcClient();}
async function fetchPresence(deviceToken){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);timer.unref();try{return await fetch(`${endpoint}/api/presence/device`,{headers:{Authorization:`Bearer ${deviceToken}`},signal:controller.signal});}finally{clearTimeout(timer);}}
async function pair(input){const code=(input||'').replace(/\s/g,'');if(!/^\d{8}$/.test(code))throw new Error('Use o código de 8 dígitos exibido pelo Aurora.');const response=await fetch(`${endpoint}/api/presence/pair/claim`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,deviceName:`${os.hostname()} · Discord`})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Não foi possível parear.');await saveConfig({protectedToken:protectSecret(value.token)});console.log('Aurora conectado. Agora execute npm start.');}
async function main(){
  if(process.argv[2]==='pair'){let value=process.argv[3];if(!value){const terminal=readline.createInterface({input:process.stdin,output:process.stdout});value=await terminal.question('Código exibido no Aurora: ');terminal.close();}return pair(value);}
  const config=await readConfig();if(!config.protectedToken)throw new Error('Este PC ainda não foi pareado. Execute npm run pair.');const deviceToken=unprotectSecret(config.protectedToken);
  let rpc=await createDiscordClient();let last='';let timer;let closing=false;let lastError='';let socialFailures=0;const startedAt=new Date().toISOString();
  const runtimeBase=()=>({pid:process.pid,transport:rpc.transport,startedAt,heartbeatAt:new Date().toISOString()});
  async function useRpcFallback(){try{await rpc.destroy();}catch{/* Best effort. */}rpc=await createRpcClient();last='';socialFailures=0;console.log('[Aurora] Discord recusou o modo Ouvindo; presença mantida pelo modo compatível.');}
  async function sync(){try{const response=await fetchPresence(deviceToken);if(response.status===401)throw new Error('Pareamento revogado. Abra o Aurora e conecte este PC novamente.');if(!response.ok)throw new Error('Aurora Presence indisponível.');const value=await response.json();const activity=toDiscordActivity(value.presence);const key=activityKey(activity);if(key!==last){try{if(activity)await rpc.setActivity(activity);else await rpc.clearActivity();socialFailures=0;}catch(error){if(rpc.transport==='social-sdk'&&++socialFailures>=2){await useRpcFallback();if(activity)await rpc.setActivity(activity);else await rpc.clearActivity();}else throw error;}last=key;}lastError='';await saveRuntime({...runtimeBase(),connected:true,presenceActive:Boolean(activity),lastSyncedAt:new Date().toISOString(),track:activity?{title:activity.details,artist:activity.state}:null});}catch(error){const message=error.name==='AbortError'?'Aurora Presence demorou para responder.':error.message;await saveRuntime({...runtimeBase(),connected:false,error:message});if(message!==lastError){console.error(`[Aurora] ${message}`);lastError=message;}}finally{if(!closing)timer=setTimeout(()=>void sync(),5000);}}
  console.log(`Aurora conectado ao Discord via ${rpc.transport==='social-sdk'?'Social SDK oficial':'RPC compatível'}.`);void sync();
  const close=async()=>{if(closing)return;closing=true;clearTimeout(timer);try{await rpc.clearActivity();await rpc.destroy();}catch{/* Shutdown remains best effort. */}finally{await clearRuntime();process.exit(0);}};process.on('SIGINT',close);process.on('SIGTERM',close);
}
main().catch(error=>{console.error(`Aurora Discord Companion: ${error.message}`);process.exitCode=1;});
