import { Download, Heart, Play, Plus, Search } from './icons';
import { Cover } from './components';
import type { Track } from './types';

type Collection={id:string;title:string;tracks:Track[]};
function TrackShelf({title,subtitle,tracks,play}:{title:string;subtitle:string;tracks:Track[];play:(track:Track,source:Track[])=>void}){if(!tracks.length)return null;return <section className="discovery-section"><div className="home-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="track-shelf">{tracks.slice(0,6).map(track=><button className="track-card" key={track.id} onClick={()=>play(track,tracks)}><span className="track-card-cover"><Cover artwork={track.artwork}/><span className="track-card-play"><Play fill="currentColor"/></span></span><b>{track.title}</b><small>{track.artist}</small></button>)}</div></section>;}

export function HomeStage({track,liked,like,play,playTrack,collections,recent,favorites,discovery,open,create,browse,search,install}:{track:Track;liked:boolean;like:()=>void;play:()=>void;playTrack:(track:Track,source:Track[])=>void;collections:Collection[];recent:Track[];favorites:Track[];discovery:Track[];open:(id:string)=>void;create:()=>void;browse:()=>void;search:()=>void;install?:()=>void}) {
  const seen=new Set([...recent,...favorites].map(item=>item.id));const fresh=discovery.filter(item=>!seen.has(item.id));
  return <><section className="aurora-banner" aria-label="Aurora Music"><img src={`${import.meta.env.BASE_URL}aurora-icon.svg`} alt=""/><div><small>AURORA MUSIC</small><h2>O seu som começa aqui.</h2><p>Retome, descubra e leve sua biblioteca para qualquer tela.</p><div className="banner-actions"><button className="outline-button" onClick={search}><Search/>Explorar músicas</button>{install&&<button className="outline-button install-button" onClick={install}><Download/>Instalar app</button>}</div></div></section>
    <div className="home-feature"><Cover artwork={track.artwork}/><div><small>CONTINUE OUVINDO · YOUTUBE</small><h1>{track.title}</h1><p>{track.artist}</p><div className="feature-actions"><button className="primary-button" onClick={play}><Play fill="currentColor"/>Reproduzir</button><button className="feature-heart" aria-label="Curtir faixa em destaque" aria-pressed={liked} onClick={like}><Heart fill={liked?'currentColor':'none'}/></button></div></div></div>
    <TrackShelf title="Ouvidas recentemente" subtitle="Volte para o que já entrou no seu ritmo." tracks={recent.filter(item=>item.id!==track.id)} play={playTrack}/>
    <TrackShelf title="Favoritas em rotação" subtitle="Suas curtidas, prontas em qualquer navegador conectado." tracks={favorites} play={playTrack}/>
    <TrackShelf title="Comece por aqui" subtitle="Uma seleção do Aurora para explorar agora." tracks={fresh.length?fresh:discovery} play={playTrack}/>
    <section className="discovery-section"><div className="home-heading"><div><h2>Suas playlists</h2><p>Organize o que merece tocar de novo.</p></div><button className="text-button" onClick={browse}>Ver biblioteca</button></div>{collections.length?<div className="playlist-shelf">{collections.slice(0,4).map(item=><button className="playlist-tile" key={item.id} onClick={()=>open(item.id)}><Cover artwork={item.tracks[0]?.artwork}/><b>{item.title}</b><small>{item.tracks.length} faixas · Aurora</small></button>)}</div>:<div className="home-empty"><p>Seu som, organizado do seu jeito. Crie uma playlist para começar.</p><button className="outline-button" onClick={create}><Plus/>Nova playlist</button></div>}</section>
  </>;
}
