import { Download, Heart, Monitor, Play, Plus, Search } from './icons';
import { Cover } from './components';
import type { Track } from './types';

type Collection={id:string;title:string;tracks:Track[]};
function TrackShelf({title,subtitle,tracks,play}:{title:string;subtitle:string;tracks:Track[];play:(track:Track,source:Track[])=>void}){if(!tracks.length)return null;return <section className="discovery-section"><div className="home-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="track-shelf">{tracks.slice(0,6).map(track=><button className="track-card" key={track.id} onClick={()=>play(track,tracks)}><span className="track-card-cover"><Cover artwork={track.artwork}/><span className="track-card-play"><Play fill="currentColor"/></span></span><b>{track.title}</b><small>{track.artist}</small></button>)}</div></section>;}

export function HomeStage({track,liked,like,play,playTrack,collections,recent,favorites,discovery,open,create,browse,search,install,connect}:{track:Track;liked:boolean;like:()=>void;play:()=>void;playTrack:(track:Track,source:Track[])=>void;collections:Collection[];recent:Track[];favorites:Track[];discovery:Track[];open:(id:string)=>void;create:()=>void;browse:()=>void;search:()=>void;install?:()=>void;connect:()=>void}) {
  const seen=new Set([...recent,...favorites].map(item=>item.id));const fresh=discovery.filter(item=>!seen.has(item.id));
  return <><section className="home-feature" aria-label="Continue ouvindo"><div className="feature-art"><Cover artwork={track.artwork}/></div><div className="feature-copy"><small>TOCANDO AGORA · AURORA</small><h1>{track.title}</h1><p>{track.artist}</p><div className="feature-actions"><button className="primary-button" onClick={play}><Play fill="currentColor"/>Reproduzir</button><button className="feature-heart" aria-label="Curtir faixa em destaque" aria-pressed={liked} onClick={like}><Heart fill={liked?'currentColor':'none'}/></button><button className="feature-connect" aria-label="Abrir Aurora Connect" onClick={connect}><Monitor/></button></div><div className="feature-shortcuts"><button onClick={search}><Search/>Descobrir músicas</button>{install&&<button onClick={install}><Download/>Instalar Aurora</button>}</div></div></section>
    <TrackShelf title="Ouvidas recentemente" subtitle="Volte para o que já entrou no seu ritmo." tracks={recent.filter(item=>item.id!==track.id)} play={playTrack}/>
    <TrackShelf title="Mix feito pra você" subtitle="Favoritas e descobertas para manter o seu ritmo." tracks={[...favorites,...(fresh.length?fresh:discovery)].filter((item,index,array)=>array.findIndex(track=>track.id===item.id)===index)} play={playTrack}/>
    <section className="discovery-section"><div className="home-heading"><div><h2>Suas playlists</h2><p>Organize o que merece tocar de novo.</p></div><button className="text-button" onClick={browse}>Ver biblioteca</button></div>{collections.length?<div className="playlist-shelf">{collections.slice(0,4).map(item=><button className="playlist-tile" key={item.id} onClick={()=>open(item.id)}><Cover artwork={item.tracks[0]?.artwork}/><b>{item.title}</b><small>{item.tracks.length} faixas · Aurora</small></button>)}</div>:<div className="home-empty"><p>Seu som, organizado do seu jeito. Crie uma playlist para começar.</p><button className="outline-button" onClick={create}><Plus/>Nova playlist</button></div>}</section>
  </>;
}
