import { useEffect, useMemo, useRef, useState } from 'react';
import type { Track } from './types';
import { activeLyric, parseLyrics, searchLyrics, type LyricsRecord } from './lyrics';
export function LyricsPanel({track,position}:{track:Track;position:number}){
 const [title,setTitle]=useState(track.title),[artist,setArtist]=useState(track.artist.replace(/\s*-\s*Topic$/i, ''));
 const [records,setRecords]=useState<LyricsRecord[]>([]),[selected,setSelected]=useState<LyricsRecord|null>(null);
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[follow,setFollow]=useState(true),[offset,setOffset]=useState(0);
 const request=useRef<AbortController|null>(null),active=useRef<HTMLParagraphElement|null>(null);
 useEffect(()=>()=>{request.current?.abort();request.current=null;},[]);
 async function lookup(){
  request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setStatus('Buscando letras…');setRecords([]);setSelected(null);
  const timeout=setTimeout(()=>controller.abort(),15000);
  try{const items=await searchLyrics(title,artist,controller.signal);if(request.current!==controller)return;setRecords(items);setStatus(items.length?'Selecione a versão correspondente à música.':'Nenhuma letra encontrada. Ajuste o título ou o artista e tente novamente.');}
  catch(error){if(request.current===controller)setStatus(controller.signal.aborted?'A consulta demorou demais. Tente novamente.':error instanceof TypeError?'Não foi possível acessar o serviço de letras. Verifique sua conexão ou bloqueadores e tente novamente.':(error as Error).message);}
  finally{clearTimeout(timeout);if(request.current===controller)setBusy(false);}
 }
 const lines=useMemo(()=>parseLyrics(selected?.syncedLyrics ?? ''),[selected]);const index=activeLyric(lines,position-offset);
 useEffect(()=>{if(follow&&active.current)active.current.scrollIntoView({block:'nearest',behavior:'instant'});},[index,follow,selected]);
 return <section className="lyrics-panel" aria-label="Letras da música"><h3>Letras</h3><p className="lyrics-help">Busque e escolha a versão da faixa. Títulos de vídeos podem precisar de ajustes.</p><form onSubmit={event=>{event.preventDefault();void lookup();}}><label>Música<input value={title} onChange={event=>setTitle(event.target.value)} required maxLength={200}/></label><label>Artista<input value={artist} onChange={event=>setArtist(event.target.value)} maxLength={200}/></label><button className="outline-button" disabled={busy}>Buscar letra</button></form><p role="status">{status}</p>{!selected&&records.length>0&&<div className="lyrics-results">{records.map(record=><button key={record.id} onClick={()=>{setSelected(record);setStatus('');}}><b>{record.trackName}</b><small>{record.artistName} · {record.albumName||'Álbum não informado'} · {Math.floor(record.duration/60)}:{String(Math.floor(record.duration%60)).padStart(2,'0')} · #{record.id} · {record.instrumental?'Instrumental':record.syncedLyrics?'Sincronizada':'Texto'}</small></button>)}</div>}{selected&&<><div className="lyrics-heading"><b>{selected.trackName}</b><button className="text-button" onClick={()=>setSelected(null)}>Trocar versão</button></div>{selected.instrumental?<p>Faixa instrumental · sem letra.</p>:lines.length>0?<><label className="lyrics-follow"><input type="checkbox" checked={follow} onChange={event=>setFollow(event.target.checked)}/>Acompanhar reprodução</label><label>Ajuste de sincronização (segundos)<input type="number" min={-120} max={120} step={0.5} value={offset} onChange={event=>setOffset(Math.max(-120,Math.min(120,Number(event.target.value)||0)))}/></label><small>Use um valor positivo se a voz começar mais tarde no vídeo.</small><div className="lyrics-text" tabIndex={0} aria-label="Letra sincronizada">{lines.map((line,i)=><p key={i} ref={i===index?active:undefined} className={i===index?'current-line':''} aria-current={i===index?'true':undefined}>{line.text||'♪'}</p>)}</div></>:<div className="lyrics-text plain" tabIndex={0} aria-label="Letra da música">{selected.plainLyrics||'Letra indisponível.'}</div>}</>}<a className="lyrics-source" href="https://lrclib.net" target="_blank" rel="noreferrer">Letras por LRCLIB</a></section>;
}
