import { useEffect,useMemo,useState } from 'react';import { Play,Plus,Profile,Search,Users } from './icons';import { Cover } from './components';import { socialRequest,type SocialState } from './social-api';import type { Track } from './types';
export function SocialStage({token,name,avatar,current,play,notify}:{token:string|null;name:string;avatar?:string;current:Track;play:(track:Track,source:Track[])=>void;notify:(value:string)=>void}){const [state,setState]=useState<SocialState|null>(null),[busy,setBusy]=useState(false),[handle,setHandle]=useState(''),[bio,setBio]=useState(''),[query,setQuery]=useState(''),[playlist,setPlaylist]=useState(''),[invite,setInvite]=useState<Record<string,string>>({});
  const act=async(body?:Record<string,unknown>)=>{if(!token)return;setBusy(true);try{setState(await socialRequest(token,body));}catch(error){notify((error as Error).message);}finally{setBusy(false);}};useEffect(()=>{if(token)void act();else setState(null);},[token]);
  const profiles=useMemo(()=>state?.profiles.filter(item=>`${item.handle} ${item.displayName}`.toLowerCase().includes(query.toLowerCase()))??[],[state,query]);
  if(!token)return <div className="social-gate"><Users/><h2>Sua turma também mora na música.</h2><p>Conecte sua conta para criar um perfil, seguir pessoas e montar playlists em conjunto.</p></div>;
  if(!state)return <div className="social-gate"><Users/><h2>{busy?'Abrindo a comunidade…':'Aurora Social'}</h2></div>;
  if(!state.me)return <section className="social-onboarding"><span className="social-avatar">{avatar?<img src={avatar} alt=""/>:<Profile/>}</span><div><small>AURORA SOCIAL</small><h2>Escolha como vão te encontrar.</h2><p>Seu perfil será público. Sua conta Google e seu e-mail nunca aparecem.</p><form onSubmit={event=>{event.preventDefault();void act({type:'profile',handle,displayName:name,bio,avatar});}}><label>@usuário<input value={handle} onChange={event=>setHandle(event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))} minLength={3} maxLength={24} required/></label><label>Bio<input value={bio} onChange={event=>setBio(event.target.value)} maxLength={160} placeholder="O que move o seu som?"/></label><button className="primary-button" disabled={busy}>Criar meu perfil</button></form></div></section>;
  return <div className="social-stage"><section className="social-profile"><span className="social-avatar">{state.me.avatar?<img src={state.me.avatar} alt=""/>:<Profile/>}</span><div><small>SEU PERFIL</small><h2>@{state.me.handle}</h2><p>{state.me.bio||'Sua identidade musical no Aurora.'}</p><span>{state.me.followers} seguidores · {state.me.following} seguindo</span></div></section>
    <section className="social-section"><div className="home-heading"><div><h2>Encontre sua turma</h2><p>Siga pessoas e descubra o que elas estão construindo.</p></div></div><label className="social-search"><Search/><input aria-label="Buscar perfis" placeholder="Buscar @usuário" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="profile-grid">{profiles.map(profile=><article className="profile-card" key={profile.handle}><span className="social-avatar small">{profile.avatar?<img src={profile.avatar} alt=""/>:<Profile/>}</span><div><b>{profile.displayName}</b><small>@{profile.handle}</small><p>{profile.bio||'Ouvindo no Aurora.'}</p></div><button className={profile.followedByMe?'outline-button':'primary-button'} disabled={busy} onClick={()=>void act({type:'follow',handle:profile.handle,following:!profile.followedByMe})}>{profile.followedByMe?'Seguindo':'Seguir'}</button></article>)}</div></section>
    <section className="social-section"><div className="home-heading"><div><h2>Playlists compartilhadas</h2><p>Uma seleção feita por todo mundo que você convidar.</p></div></div><form className="social-create" onSubmit={event=>{event.preventDefault();void act({type:'create-playlist',title:playlist});setPlaylist('');}}><input aria-label="Nome da playlist compartilhada" value={playlist} onChange={event=>setPlaylist(event.target.value)} placeholder="Nome da nova playlist" required/><button className="primary-button" disabled={busy}><Plus/>Criar em conjunto</button></form><div className="collab-list">{state.playlists.map(item=><article className="collab-card" key={item.id}><div className="collab-head"><div><small>POR @{item.ownerHandle}</small><h3>{item.title}</h3><p>{item.members.length?`Com ${item.members.map(value=>'@'+value).join(', ')}`:'Só você por enquanto'}</p></div>{item.tracks[0]&&<Cover artwork={item.tracks[0].track.artwork}/>}</div><div className="collab-actions"><button className="outline-button" onClick={()=>void act({type:'add-track',playlistId:item.id,track:current})}><Plus/>Adicionar faixa atual</button><form onSubmit={event=>{event.preventDefault();void act({type:'invite',playlistId:item.id,handle:invite[item.id]});}}><input aria-label={`Convidar para ${item.title}`} value={invite[item.id]??''} onChange={event=>setInvite(value=>({...value,[item.id]:event.target.value}))} placeholder="@usuário"/><button disabled={busy}><Users/>Convidar</button></form></div><div className="collab-tracks">{item.tracks.map(entry=><button key={entry.track.id} onClick={()=>play(entry.track,item.tracks.map(value=>value.track))}><Cover artwork={entry.track.artwork}/><span><b>{entry.track.title}</b><small>{entry.track.artist} · adicionada por @{entry.addedBy}</small></span><Play/></button>)}{!item.tracks.length&&<p>Adicione a faixa que está tocando para começar.</p>}</div></article>)}</div></section></div>;
}
