import {useEffect,useMemo,useRef,useState} from 'react';
import {Play,Plus,Profile,Search,Users} from './icons';
import {Cover} from './components';
import {readPublicProfile,socialRequest,type PublicSocialProfile,type SocialActivity,type SocialState} from './social-api';
import type {Track} from './types';

const activityText=(item:SocialActivity)=>item.type==='joined'?'entrou para o Aurora':item.type==='playlist'?`criou ${item.playlistTitle}`:item.type==='joined-playlist'?`entrou em ${item.playlistTitle}`:item.type==='track'?`adicionou ${item.track?.title} em ${item.playlistTitle}`:'começou a seguir um perfil';
const profileUrl=(handle:string)=>`${location.origin}${location.pathname}?view=social&profile=${encodeURIComponent(handle)}`;
const inviteUrl=(token:string)=>`${location.origin}${location.pathname}?view=social&invite=${encodeURIComponent(token)}`;
async function share(title:string,text:string,url:string){if(navigator.share){await navigator.share({title,text,url});return;}await navigator.clipboard.writeText(url);}

function Avatar({src,small=false}:{src?:string;small?:boolean}){return <span className={`social-avatar${small?' small':''}`}>{src?<img src={src} alt=""/>:<Profile/>}</span>;}
function ActivityFeed({items,play}:{items:SocialActivity[];play:(track:Track)=>void}){return <div className="activity-feed">{items.map(item=><article key={item.id}><Avatar src={item.actorAvatar} small/><div><b>@{item.actorHandle}</b><p>{activityText(item)}</p><time dateTime={item.at}>{new Date(item.at).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</time></div>{item.track&&<button aria-label={`Tocar ${item.track.title}`} onClick={()=>play(item.track!)}><Cover artwork={item.track.artwork}/><Play/></button>}</article>)}{!items.length&&<p className="empty-social">Siga perfis para construir seu feed musical.</p>}</div>;}
function PublicProfile({handle,play,notify,onClose}:{handle:string;play:(track:Track)=>void;notify:(value:string)=>void;onClose:()=>void}){const [value,setValue]=useState<PublicSocialProfile|null>(null);useEffect(()=>{let active=true;readPublicProfile(handle).then(result=>{if(active)setValue(result);}).catch(error=>notify((error as Error).message));return()=>{active=false;};},[handle]);if(!value)return <div className="social-gate"><Profile/><h2>Carregando @{handle}…</h2></div>;return <div className="social-stage"><button className="outline-button" onClick={onClose}>← Voltar à comunidade</button><section className="social-profile public-profile"><Avatar src={value.profile.avatar}/><div><small>PERFIL PÚBLICO</small><h2>@{value.profile.handle}</h2><b>{value.profile.displayName}</b><p>{value.profile.bio||'Sua identidade musical no Aurora.'}</p><span>{value.profile.followers} seguidores · {value.profile.following} seguindo</span></div></section><section className="social-section"><h2>Atividade recente</h2><ActivityFeed items={value.activity} play={play}/></section><section className="social-section"><h2>Playlists criadas</h2><div className="public-playlists">{value.playlists.map(item=><article key={item.id}><b>{item.title}</b><span>{item.tracks} faixas</span></article>)}{!value.playlists.length&&<p className="empty-social">Nenhuma playlist pública ainda.</p>}</div></section></div>;}

export function SocialStage({token,name,avatar,current,play,notify}:{token:string|null;name:string;avatar?:string;current:Track;play:(track:Track,source:Track[])=>void;notify:(value:string)=>void}){
  const [state,setState]=useState<SocialState|null>(null),[busy,setBusy]=useState(false),[handle,setHandle]=useState(''),[bio,setBio]=useState(''),[displayName,setDisplayName]=useState(name),[profileAvatar,setProfileAvatar]=useState(avatar??''),[editing,setEditing]=useState(false),[query,setQuery]=useState(''),[playlist,setPlaylist]=useState(''),[invite,setInvite]=useState<Record<string,string>>({});
  const params=new URLSearchParams(location.search),publicHandle=params.get('profile'),inviteToken=params.get('invite'),joined=useRef('');
  const act=async(body?:Record<string,unknown>)=>{if(!token)return false;setBusy(true);try{setState(await socialRequest(token,body));return true;}catch(error){notify((error as Error).message);return false;}finally{setBusy(false);}};
  useEffect(()=>{if(token)void act();else setState(null);},[token]);
  useEffect(()=>{if(!token||!state?.me||!inviteToken||joined.current===inviteToken)return;joined.current=inviteToken;void act({type:'join-playlist',token:inviteToken}).then(ok=>{if(ok)notify('Você entrou na playlist compartilhada.');});},[token,state?.me?.handle,inviteToken]);
  const profiles=useMemo(()=>state?.profiles.filter(item=>`${item.handle} ${item.displayName}`.toLowerCase().includes(query.toLowerCase()))??[],[state,query]);
  const openProfile=(value:string)=>{const url=new URL(location.href);url.searchParams.set('view','social');url.searchParams.set('profile',value);history.pushState({},'',url);location.reload();};
  const closeProfile=()=>{const url=new URL(location.href);url.searchParams.delete('profile');history.pushState({},'',url);location.reload();};
  if(publicHandle)return <PublicProfile handle={publicHandle} notify={notify} onClose={closeProfile} play={track=>play(track,[track])}/>;
  if(!token)return <div className="social-gate"><Users/><h2>Sua turma também mora na música.</h2><p>Entre com Google para criar um perfil, seguir pessoas e montar playlists em conjunto.</p>{inviteToken&&<strong>Seu convite ficará pronto depois do login.</strong>}</div>;
  if(!state)return <div className="social-gate"><Users/><h2>{busy?'Abrindo a comunidade…':'Aurora Social'}</h2></div>;
  if(!state.me)return <section className="social-onboarding"><Avatar src={avatar}/><div><small>1 MINUTO · AURORA SOCIAL</small><h2>Escolha como vão te encontrar.</h2><p>Seu @, nome, foto, bio e atividade musical serão públicos. Seu e-mail e sua conta Google nunca aparecem.</p><form onSubmit={event=>{event.preventDefault();void act({type:'profile',handle,displayName:name,bio,avatar});}}><label>@usuário<input value={handle} onChange={event=>setHandle(event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))} minLength={3} maxLength={24} placeholder="seu_nome" required/></label><label>Bio<input value={bio} onChange={event=>setBio(event.target.value)} maxLength={160} placeholder="O que move o seu som?"/></label><button className="primary-button" disabled={busy}>Entrar na comunidade</button></form></div></section>;
  const beginEdit=()=>{setHandle(state.me!.handle);setDisplayName(state.me!.displayName);setBio(state.me!.bio);setProfileAvatar(state.me!.avatar);setEditing(true);};
  return <div className="social-stage"><section className="social-profile"><Avatar src={state.me.avatar}/><div><small>SEU PERFIL</small><h2>@{state.me.handle}</h2><b>{state.me.displayName}</b><p>{state.me.bio||'Sua identidade musical no Aurora.'}</p><span>{state.me.followers} seguidores · {state.me.following} seguindo</span></div><div className="profile-actions"><button className="outline-button" onClick={beginEdit}>Editar perfil</button><button className="outline-button" onClick={()=>void share('Meu perfil no Aurora',`Veja o que @${state.me!.handle} está ouvindo no Aurora.`,profileUrl(state.me!.handle)).then(()=>notify('Link do perfil pronto para compartilhar.')).catch(()=>{})}>Compartilhar perfil</button></div></section>
    {editing&&<section className="profile-editor" aria-label="Editar perfil"><div className="profile-editor-head"><div><small>PERSONALIZE SUA PRESENÇA</small><h2>Editar perfil</h2></div><button aria-label="Fechar edição" onClick={()=>setEditing(false)}>×</button></div><form onSubmit={event=>{event.preventDefault();void act({type:'profile',handle,displayName,bio,avatar:profileAvatar}).then(ok=>{if(ok){setEditing(false);notify('Perfil atualizado.');}});}}><label>@usuário<input value={handle} onChange={event=>setHandle(event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))} minLength={3} maxLength={24} required/></label><label>Nome público<input value={displayName} onChange={event=>setDisplayName(event.target.value)} maxLength={60} required/></label><label>Bio<textarea value={bio} onChange={event=>setBio(event.target.value)} maxLength={160} rows={3}/><small>{bio.length}/160</small></label><label>URL da foto<input type="url" value={profileAvatar} onChange={event=>setProfileAvatar(event.target.value)} placeholder="https://…"/></label><div><button type="button" className="outline-button" onClick={()=>setEditing(false)}>Cancelar</button><button className="primary-button" disabled={busy}>Salvar alterações</button></div></form></section>}
    <section className="social-section"><div className="home-heading"><div><h2>No seu radar</h2><p>Atividade sua e de quem você segue.</p></div></div><ActivityFeed items={state.feed} play={track=>play(track,[track])}/></section>
    <section className="social-section"><div className="home-heading"><div><h2>Encontre sua turma</h2><p>Siga pessoas e abra perfis públicos.</p></div></div><label className="social-search"><Search/><input aria-label="Buscar perfis" placeholder="Buscar @usuário" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="profile-grid">{profiles.map(profile=><article className="profile-card" key={profile.handle}><button className="profile-identity" onClick={()=>openProfile(profile.handle)}><Avatar src={profile.avatar} small/><span><b>{profile.displayName}</b><small>@{profile.handle}</small><p>{profile.bio||'Ouvindo no Aurora.'}</p></span></button><button className={profile.followedByMe?'outline-button':'primary-button'} disabled={busy} onClick={()=>void act({type:'follow',handle:profile.handle,following:!profile.followedByMe})}>{profile.followedByMe?'Seguindo':'Seguir'}</button></article>)}</div></section>
    <section className="social-section"><div className="home-heading"><div><h2>Playlists compartilhadas</h2><p>Crie, mande o link e construam juntos.</p></div></div><form className="social-create" onSubmit={event=>{event.preventDefault();void act({type:'create-playlist',title:playlist});setPlaylist('');}}><input aria-label="Nome da playlist compartilhada" value={playlist} onChange={event=>setPlaylist(event.target.value)} placeholder="Nome da nova playlist" required/><button className="primary-button" disabled={busy}><Plus/>Criar em conjunto</button></form><div className="collab-list">{state.playlists.map(item=><article className="collab-card" key={item.id}><div className="collab-head"><div><small>POR @{item.ownerHandle}</small><h3>{item.title}</h3><p>{item.members.length?`Com ${item.members.map(value=>'@'+value).join(', ')}`:'Só você por enquanto'}</p></div>{item.tracks[0]&&<Cover artwork={item.tracks[0].track.artwork}/>}</div><div className="collab-actions"><button className="outline-button" onClick={()=>void act({type:'add-track',playlistId:item.id,track:current})}><Plus/>Adicionar faixa atual</button>{item.inviteToken?<button className="outline-button" onClick={()=>void share(item.title,'Entre na minha playlist colaborativa do Aurora.',inviteUrl(item.inviteToken!)).then(()=>notify('Link de convite pronto para compartilhar.')).catch(()=>{})}><Users/>Compartilhar convite</button>:item.ownerHandle===state.me!.handle&&<button className="outline-button" onClick={()=>void act({type:'rotate-invite',playlistId:item.id})}><Users/>Criar link de convite</button>}<form onSubmit={event=>{event.preventDefault();void act({type:'invite',playlistId:item.id,handle:invite[item.id]});}}><input aria-label={`Convidar para ${item.title}`} value={invite[item.id]??''} onChange={event=>setInvite(value=>({...value,[item.id]:event.target.value}))} placeholder="@usuário"/><button disabled={busy}><Users/>Convidar</button></form></div><div className="collab-tracks">{item.tracks.map(entry=><button key={entry.track.id} onClick={()=>play(entry.track,item.tracks.map(value=>value.track))}><Cover artwork={entry.track.artwork}/><span><b>{entry.track.title}</b><small>{entry.track.artist} · adicionada por @{entry.addedBy}</small></span><Play/></button>)}{!item.tracks.length&&<p>Adicione a faixa que está tocando para começar.</p>}</div></article>)}</div></section></div>;
}
