import type { Track } from './types';
const ENDPOINT=(import.meta.env.VITE_CONNECT_ENDPOINT??'').replace(/\/$/,'');
export type SocialProfile={handle:string;displayName:string;bio:string;avatar:string;followers:number;following:number;followedByMe:boolean;matchReady:boolean};
export type SocialActivity={id:string;type:'joined'|'followed'|'playlist'|'joined-playlist'|'track';actorHandle:string;actorName:string;actorAvatar:string;playlistTitle?:string;track?:Track;at:string};
export type SocialPlaylist={id:string;title:string;ownerHandle:string;members:string[];tracks:{track:Track;addedBy:string;addedAt:string}[];updatedAt:string;canEdit:boolean;inviteToken?:string};
export type SocialState={me:SocialProfile|null;profiles:SocialProfile[];playlists:SocialPlaylist[];feed:SocialActivity[]};
export type PublicSocialProfile={profile:SocialProfile;activity:SocialActivity[];playlists:{id:string;title:string;tracks:number;updatedAt:string}[]};
export type SocialMatch={score:number;with:{handle:string;displayName:string;avatar:string};sharedTracks:Track[];sharedArtists:string[];discoveries:Track[];explanation:string};
export async function socialRequest(token:string,body?:Record<string,unknown>):Promise<SocialState>{const response=await fetch(`${ENDPOINT}/api/social`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});const value=await response.json().catch(()=>({error:'Aurora Social indisponível.'}));if(!response.ok)throw new Error(value.error??'Aurora Social indisponível.');return value;}
export async function readPublicProfile(handle:string):Promise<PublicSocialProfile>{const response=await fetch(`${ENDPOINT}/api/social/public?handle=${encodeURIComponent(handle)}`,{signal:AbortSignal.timeout(10000)});const value=await response.json().catch(()=>({error:'Perfil indisponível.'}));if(!response.ok)throw new Error(value.error??'Perfil indisponível.');return value;}
export async function readSocialMatch(token:string,handle:string):Promise<SocialMatch>{const response=await fetch(`${ENDPOINT}/api/social/match?handle=${encodeURIComponent(handle)}`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(10000)});const value=await response.json().catch(()=>({error:'Aurora Match indisponível.'}));if(!response.ok)throw new Error(value.error??'Aurora Match indisponível.');return value;}
